### ISSUE TITLE
Jade renamed to Pug

### ISSUE THREAD

**Issue by ricpelo** [jacmoe/yii2-tale-jade#1]
Hi! Jade project has been renamed to Pug (https://pugjs.org/). Does your extension works well with the new changes? Do you plan to update it? Thanks!

**Comment by jacmoe** [comment]
I will, when Tale Jade does. :)

A pity that they were forced to change their name.
Probably means that we have to rename all our projects as well..

**Comment by jacmoe** [comment]
This project has now moved to https://github.com/jacmoe/yii2-pug - expect some very wet paint for a (hopefully!) very short while! 😄
